# Generated by Django 5.2.4 on 2025-07-12 23:00

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_id', models.IntegerField()),
                ('receiver_name', models.CharField(max_length=100)),
                ('pickup_address', models.TextField()),
                ('delivery_address', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('assigned_driver_id', models.IntegerField(blank=True, null=True)),
                ('tracking_id', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
