# Generated by Django 5.2.4 on 2025-07-12 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='tracking_id',
            field=models.CharField(db_index=True, editable=False, max_length=20, unique=True),
        ),
    ]
